<?php require("Views/template/header.phtml") ?>
<!-- Page content-->
<div class="container-fluid">
    <h1 class="mt-4 text-center">Commit History</h1>
    <br>

    <br>


</div>

<div class="album py-5 bg-light">
    <div class="container">

        <div class="d-flex justify-content-center">
            <form method="post" action="" class="form">
                <div class="row pb-2">
                    <!--
                     <label for="searchVal" class="h5 col-sm-5">Search by name:</label>
                     -->
                    <div class="">
                        <h3 class="">Search Commits</h3>
                    </div>
                </div>

                <div class="d-flex justify-content-center pb-2">
                    <input class="" type="text" id="myInput" onkeyup="myFunction()" placeholder="Search by author name.." title="Type in a name">
                </div>

            </form>

            <div class="row ps-5">
                <form method="POST" action="">
                    <h4>Filters</h4>
                    <input type="checkbox" id="author" name="author" value="author" onchange="this.form.submit()">
                    <label for="author"> Author name</label><br>
                    <input type="checkbox" id="msg" name="msg" value="msg" onchange="this.form.submit()">
                    <label for="msg"> Messages</label><br>
                    <input type="checkbox" id="date" name="date" value="date" onchange="this.form.submit()">
                    <label for="date"> Date</label><br>
                    <input type="checkbox" id="commit" name="commit" value="commit" onchange="this.form.submit()">
                    <label for="commit"> Commit</label><br>
                    <input type="checkbox" id="all" name="all" value="all" onchange="this.form.submit()">
                    <label for="all"> Show All</label><br><br>

                </form>
            </div>

        </div>

            <div class="col-md-12">

                <table class="table table-bordered table-striped align-middle pt-4" id="myTable">
                    <thead class="table-dark align-middle" >
                    <tr>
                        <th style="width:15%;">Author</th>
                        <th style="width:45%;">Message</th>
                        <th style="width:15%;">Date</th>
                        <th style="width:25%;">Commit</th>
                    </tr>
                    </thead>

                    <tbody>

                    <?php /*
                    $repository = $data;
                    foreach($commitData as $value):
                        $commit = $value['commit'];
                        $author = $commit['author'];
                        echo "
                             <tr>
                                <td>".$author['name']."</td>
                                <td>".$commit['message']."</td>
                                <td>".$author['date']."</td>
                                <td>".$value['sha']."</td>
                             </tr>";
                    endforeach; */
                    require_once("commitsCard.phtml");
                    ?>
                    </tbody>


                </table>

                <?php
                        require('returnButton.phtml')
                ?>

            </div>
    </div>
</div>





<script>
    function myFunction() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
</script>


<?php require ('template/footer.phtml') ?>

