
<div class="row pb-3">
                   <!--card to contain user info-->
                   <div class="card mb-12 box-shadow">
                        <div class="card-body text-center">
                            <h5>Commit Date: <b class="text-primary"><?=$author["date"] ?></b></h5>
                            <h5>Author Name: <b class="text-primary"><?=$author["name"] ?></b></h5>
                            <h5>Description: <b class="text-primary"><?=$commit["message"] ?></b></h5>
                        </div>
                   </div>
</div>