
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
                    '<div class="col-md-12">
                   <!--card to contain user info-->
                   <div class="card mb-12 box-shadow">
                        <div class="card-body text-center">
                            <h5>Placeholder Title: <b class="text-primary">Insert Data</b></h5>
                            <h5>Placeholder Title: <b class="text-primary">Insert Data</b></h5>
                            <h5>Placeholder Title: <b class="text-primary">Insert Data</b></h5>
                            <h5>Placeholder Title: <b class="text-primary">Insert Data</b></h5>
                            <h5>Placeholder Title: <b class="text-primary">Insert Data</b></h5>
                            <div class="d-flex justify-content-end align-items-center">
                            <form method="post" action="" class="form">
                                <div class="btn-group">
                                    <input type="hidden" name="button" value="button">
                                    <input type="submit" name="button" value="button" class="btn btn-outline-secondary" >
                                </div>
                            </form>
                            </div>
                        </div>
                    </div>
                </div>
        </div
    </div>
</div>