<?php

// all

if (isset($_POST["all"])) {
    foreach($pullsData as $value):
        $author = $value['user'];
        echo "
                             <tr>
                                <td>".$value['title']."</td>
                                <td>".$value['body']."</td>
                                <td>".$value['state']."</td>
                                <td>".$value['created_at']."</td>
                                <td>".$value['updated_at']."</td>
                                <td>".$author['login']."</td>
                             </tr>";
    endforeach;
}

// msg
elseif (isset($_POST["msg"]))
{
    foreach($pullsData as $value):
        $author = $value['user'];
        echo "
                             <tr>
                                <td></td>
                                <td>".$value['body']."</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                             </tr>";
    endforeach;
}

// author
elseif (isset($_POST["author"]))
{
    foreach($pullsData as $value):
        $author = $value['user'];
        echo "
                             <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>".$author['login']."</td>
                             </tr>";
    endforeach;}

// commit
elseif (isset($_POST["title"]))
{
    foreach ($pullsData as $value):
        $author = $value['user'];
        echo "
                             <tr>
                                <td>" . $value['title'] . "</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                             </tr>";
    endforeach;
    }

// date
elseif (isset($_POST["cdate"]))
{
    foreach($pullsData as $value):
        $author = $value['user'];
        echo "
                             <tr>
                                <td></td>
                                <td><td>
                                <td></td>
                                <td>".$value['created_at']."</td>
                                <td></td>
                                <td></td>
                             </tr>";
    endforeach;
}

elseif (isset($_POST["udate"]))
{
    foreach($pullsData as $value):
        $author = $value['user'];
        echo "
                             <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>".$value['updated_at']."</td>
                                <td></td>
                             </tr>";
    endforeach;
}