<div class="card mb-12 box-shadow">
    <div class="card-body text-center">
        <div class="d-flex justify-content-center align-items-center">
            <form method="post" action="" class="form">
                <div class="btn">
                    <input type="hidden" name="name" value="<?=$_GET["full_name"] ?>">
                    <input type="submit" name="show" value="Back to Repository Info" class="btn btn-outline-secondary" >
                </div>
            </form>

        </div>
    </div>
</div>