<?php require("Views/template/header.phtml") ?>
<!-- Page content-->
<div class="container-fluid">
    <h1 class="mt-4 text-center">Search for Repositories</h1>
</div>


<div class="album py-5 bg-light">
    <div class="container">
        <div class="d-flex justify-content-center">
            <form method="post" action="" class="form">
                <div class="form-group row pb-2">
                   <!--
                    <label for="searchVal" class="h5 col-sm-5">Search by name:</label>
                    -->
                    <div class="col-sm-5">
                        <input type="text" placeholder="Search..." name="searchTerm">
                    </div>
                </div>

                <div class="d-flex justify-content-end pb-2">
                    <input type="submit" name="searchbtn" value="Search" class="btn btn-outline-dark">
                </div>

            </form>
        </div>






        <div class="col-md-12">
            <?php if (isset($_POST["searchbtn"])){
                echo '<div class="container-fluid">';
                echo '<h2 class="mt-4 text-center">Search results for: '. $search .'</h2>';
                echo '</div>';

                if($data == null){

                }else {

                    $items = $data['items'];
                    //var_dump($items);
                    //$author = $commit['author'];

                    $i = 0;
                    while ($i <> 30) {
                        $repository = $items[$i];

                        require("repoBriefCard.phtml");
                        $i++;
                    }
                }
            }



            ?>
        </div>

    </div>
</div>

<?php require ('template/footer.phtml') ?>


