<?php require("Views/template/header.phtml") ?>
<!-- Page content-->
<div class="container-fluid">
    <h1 class="mt-4 text-center">Details About Your Repository</h1>
</div>

<div class="album py-5 bg-light">
    <div class="container">
            <div class="col-md-12">
                <?php
                $repository = $data;
                $owner = $repository['owner'];
                //var_dump($owner);
                require('repoFullCard.phtml')
                ?>


                <div class="card mb-12 box-shadow">
                    <div class="card-body text-center">
                        <div class="d-flex justify-content-center align-items-center">
                            <form method="post" action="" class="form">
                                <div class="btn">
                                    <input type="hidden" name="name" value="<?=$repository["full_name"] ?>">
                                    <input type="submit" name="back" value="Back to All Repositories" class="btn btn-outline-secondary" >
                                    <input type="submit" name="commits" value="View Commit History" class="btn btn-info" >
                                    <input type="submit" name="issues" value="View Issues" class="btn btn-info" >
                                    <input type="submit" name="pulls" value="View Pulls" class="btn btn-info">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
    </div>
</div>

<?php require ('template/footer.phtml') ?>

